### ISSUE TITLE
Web service is not waiting the DB before it is ready to accept connections.

### ISSUE THREAD

**Issue by ycemalunlu** [ycemalunlu/HelloWeb#1]
As mentioned in the update details in the commit #944aca5. The web service is throwing an error because it is trying to run the web service before DB accepts connections. 

A db health check needs to be added to solve the issue.

**Comment by ycemalunlu** [comment]
### **Fixed in commit `#3a1edbb`.**

The fix is to define the database host as its own Docker network IP address as in:

```
services:
  server:
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5
```
Here the `-h db` refers to the `db` service's own Docker IP address. With this configuration, there is often no need to pass additional flags to `pg_isready`.
